import Foundation

let supportArchs = [
    (macroDef: "__x86_64__", asmFile: "invokeNative_em64.s"),
    (macroDef: "__aarch64__", asmFile: "invokeNative_aarch64.s"),
]

let projectDir = URL(fileURLWithPath: #file)
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .deletingLastPathComponent()
let iwasmCommonArchDir = projectDir
    .appendingPathComponent("third-party/wasm-micro-runtime/core/iwasm/common/arch")
let outputDarwinInvokeNativeFile = projectDir
    .appendingPathComponent("Sources/wamr-core-darwin/invokeNative.s")
let outputLinuxInvokeNativeFile = projectDir
    .appendingPathComponent("Sources/wamr-core-linux/invokeNative.c")

let outputHeader = """

/* DO NOT MODIFY THIS FILE! IT IS AUTOMATICALLY GENERATED BY synthesize-invoke-native */


"""
var linuxOutput = """
\(outputHeader)
#ifdef __ELF__

"""

var darwinOutput = """
\(outputHeader)
#ifdef __MACH__

"""

for (index, arch) in supportArchs.enumerated() {
    let file = iwasmCommonArchDir.appendingPathComponent(arch.asmFile)
    let contents = try String(contentsOf: file)
    let parser = AsmParser(contents: contents)
    parser.parse()

    // prologue
    switch index {
    case 0:
        linuxOutput += "#if defined(\(arch.macroDef))\n"
        darwinOutput += "#if defined(\(arch.macroDef))\n"
    default:
        linuxOutput += "#elif defined(\(arch.macroDef))\n"
        darwinOutput += "#elif defined(\(arch.macroDef))\n"
    }
    linuxOutput += """
    /* Copied from https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/common/arch/\(arch.asmFile) */

    __asm__(
    \(parser.output)
    );

    """
    darwinOutput += """
    /* Copied from https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/common/arch/\(arch.asmFile) */
    \(contents)

    """

    // epilogue
    switch index {
    case supportArchs.endIndex - 1:
        linuxOutput += "#endif\n"
        darwinOutput += "#endif\n"
    default: break
    }
}

linuxOutput += """

#endif
"""

darwinOutput += """

#endif
"""
try linuxOutput.write(to: outputLinuxInvokeNativeFile, atomically: true, encoding: .utf8)
try darwinOutput.write(to: outputDarwinInvokeNativeFile, atomically: true, encoding: .utf8)
